// sidebars.ts（放在项目根目录）
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  experimentSidebar: [{ type: 'autogenerated', dirName: '.' }],

  modelSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;

