// sidebars.ts（放在项目根目录）
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 对应 metal_powder 实例
  metalSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // 对应 blender_tutorial 实例
  blenderSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;

